title: TutanDev
description: Welcome to my personal page
theme: jekyll-theme-midnight

plugins:
  - jekyll-relative-links
  
relative_links:
  enabled: true
  collections: true
  
include:
  - README.md
  - contact.md
  - ParametricSurfaces.md
  - ChromaShader.md
